vocab_baseline = 4200
vocab_tracking_start = 2026-09-03

reading_i = 41
reading_i_total = 41
reading_ii = 13
reading_ii_total = 29
reading_iii = 0
reading_iii_total = 11
grammar_i = 10
grammar_i_total = 10
grammar_ii = 7
grammar_ii_total = 11
grammar_iii = 0
grammar_iii_total = 5
grammar_iv = 0
grammar_iv_total = 7
grammar_v = 0
grammar_v_total = 3
grammar_vi = 0
grammar_vi_total = 12
